### ISSUE TITLE
[Bug]: resetAfterSubmit breaks form error messages

### ISSUE THREAD

**Issue by Mattinton** [airjp73/remix-validated-form#177] opened 2022-09-20 15:06 UTC
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [X] `zod-form-data`

### What version of these packages are you using?

Latest :) 

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/billowing-river-458mg5?file=/app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the codesandbox
2. Type any invalid text into the input
3. Press the submit button
4. See that there is no 'Required' error message
5. Remove `resetAfterSubmit` from code
6. Re run code sandbox and press submit
7. See the error message now appears

### Expected behavior

I expected there to be an error message

### Platform

- OS: macOS
- Browser: Chrome

**Comment by Mattinton** [comment] 2022-09-20 16:40
I think I've found something that may be caused by the same underlying thing. With `resetAfterSubmit` enabled if you type in an invalid input and hit enter (submitting the form) it will wipe the current value as well as displaying the error. I think `<FormResetter />` is accidentally resetting the form where I would expect it to preserve the values but show the error.

**Comment by airjp73** [comment] 2022-09-25 16:33
Hmm yeah, something fishy is definitely going on. Thank you for digging into what the cause might be.

**Comment by airjp73** [comment] 2022-09-25 16:56
Should be fixed in this release: https://github.com/airjp73/remix-validated-form/releases/tag/remix-validated-form-v4.5.6

**Closed by airjp73** 2022-09-25 16:56 UTC
Labels: bug

**Comment by Mattinton** [comment] 2022-09-25 21:05
Nice one, I'll give this a go now. Appreciate all your hard work!
