### ISSUE TITLE
[Bug]: Submit button remains disabled even after the errors are resolved

### ISSUE THREAD

**Issue by arpitdalal** [airjp73/remix-validated-form#52] opened 2022-02-03 20:15 UTC
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [X] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: ^3.4.2
- `@remix-validated-form/with-yup`: ^1.0.1

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/remix-validated-form-jzxtf?file=/app/components/Input.tsx

### Steps to Reproduce

Hit submit > You'll see errors > resolve those errors > Submit button still disabled

### Expected Behavior

Hit submit > You'll see errors > resolve those errors > Submit button enables

### Actual Behavior

Hit submit > You'll see errors > resolve those errors > Submit button still disabled

**Comment by airjp73** [comment] 2022-02-03 20:50
Thanks for the reproduction! It appears that I fixed this incidentally in the upcoming 4.0.0 release. Once I get that finished up and published, you'll be good to go :). ([sandbox](https://codesandbox.io/s/remix-validated-form-forked-nspme?file=/app/routes/index.tsx))

In the meantime, I would caution against the disable-when-invalid pattern in general. If you click the submit button when the form is invalid, the first invalid input will be focused automatically which is good UX.

**Comment by airjp73** [comment] 2022-02-04 00:08
Should be resolved in 4.0.0

**Closed by airjp73** 2022-02-04 00:08 UTC
Labels: bug

**Comment by arpitdalal** [comment] 2022-02-04 02:48
Oh that's great! And thank you very much for the codesandbox, didn't know that was a behavior, learning soo mich things while using remix. Is this the default behavior of the browser or this package does some magic?

**Comment by airjp73** [comment] 2022-02-04 02:53
If you're using native html validation there browser will do it automatically. But in this library we have to do some magic to make it happen correctly, since we're doing validation in JS.

**Comment by arpitdalal** [comment] 2022-02-04 02:55
Oh yes I see, thanks 🙏

**Comment by arpitdalal** [comment] 2022-02-04 14:32
Hey @airjp73 In you example codesandbox, why do you have `await` in front of the `validator.validate(await request.formData());`? Because if I put that in my code it yells at me that `await` has no effect on this because `validate` function doesn't return a promise.

**Comment by airjp73** [comment] 2022-02-04 14:34
@arpitdalal, in version 4.0.0 it now returns a promise. Are you still on version 3.x?

Release notes: https://github.com/airjp73/remix-validated-form/releases/tag/remix-validated-form-v4

**Comment by arpitdalal** [comment] 2022-02-04 14:35
Ah, v4 is out, my bad! Thanks
