### ISSUE TITLE
[Bug]: Should add @remix-run/server-runtime

### ISSUE THREAD

**Issue by georgiosd** [airjp73/remix-validated-form#316] opened 2023-08-11 13:54 UTC
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

"remix-validated-form": "^5.0.1"

### Please provide a link to a minimal reproduction of the issue.

https://github.com/zerotomvp/remix-ts-integrated-monorepo/tree/yarn3-pnp

### Steps to Reproduce the Bug or Issue

https://github.com/remix-run/remix/issues/6640

### Expected behavior

Should work because there is a single instance of the package.

### Platform

All

### Additional context

Please see https://github.com/remix-run/remix/issues/6640

**Comment by airjp73** [comment] 2023-08-11 16:14
That sounds reasonable. Would you have time to help with a PR?

**Comment by airjp73** [comment] 2023-09-22 13:40
Should be fixed in 5.1.2. Could you verify on your end that it's working?

**Comment by georgiosd** [comment] 2023-09-23 14:49
Hi! Sorry, I did mean to send a PR but you got to it first.

I did try upgrading to 5.1.4 and no longer see yarn's warning about the missing peer dependency, alas the project is still not working - check my repo above, I've updated it with 5.1.4.

Not sure if you want to follow up with the remix team...

**Comment by airjp73** [comment] 2023-09-23 15:22
Yeah, looks like we're getting the "`useActionData` must be used inside a data router" issue. This is happening because RVF is including a different version of remix than the main app. That's what I was trying to fix with 5.1.4 but the dependencies still aren't resolving correctly.

<img width="339" alt="Screenshot 2023-09-23 at 11 20 20 AM" src="https://github.com/airjp73/remix-validated-form/assets/25882770/74f52cef-247b-4a06-a736-3cc9fdcb11d6">

Since you're using yarn you can probably work around this by forcing remix packages to resolve to a particular version, but I definitely still need to devote some time to debugging this particular issue.

**Comment by airjp73** [comment] 2023-09-23 17:27
Version `5.1.4-beta.3` seems to be doing the trick. Could you try it out on your end?

**Comment by georgiosd** [comment] 2023-09-24 07:39
I'm afraid no change. I've updated the test repository. 

I don't mind helping out, but will probably make it easier for you to validate the fix if you try it directly :)

**Comment by airjp73** [comment] 2023-09-24 13:04
Thanks for verifying. Unfortunately there are several reproductions posted at this point and i don't have enough free time to go through every one of them and verify it directly. I'll see if I can figure out what's going on in this case.

**Comment by airjp73** [comment] 2023-09-24 13:14
Oh this is actually the main reproduction I used when debugging 😆. On my machine it is currently working -- could you provide more details about what is happening on your end? 

* Did you install the new version in both the `remix` and `shared-ui` packages in the monorepo?
* Could you post _exactly_ what error you're seeing?
* Could you post the result of `npm ls @remix-run/react`?

**Comment by georgiosd** [comment] 2023-09-27 06:45
Are you working in the `yarn3-pnp` branch on my repo?

I did add to both: https://github.com/zerotomvp/remix-ts-integrated-monorepo/commit/4223c892f5f7326463ad0eecfdd7b262ba1b012f

The error is `Error: Unable to determine form for useField. Please use it inside a ValidatedForm or pass a 'formId'.`

I can't remember how I checked this before because we've dropped Remix in the interim but I saw that it was including the (your) package twice.

Output:
```
~\Documents\remix-ts-integrated-monorepo\remix [yarn3-pnp ≡]> yarn why @remix-run/react 
└─ remix@workspace:remix
   └─ @remix-run/react@npm:1.17.1 [f6918] (via npm:^1.17.1 [f6918])
~\Documents\remix-ts-integrated-monorepo\remix [yarn3-pnp ≡]> cd ..
~\Documents\remix-ts-integrated-monorepo [yarn3-pnp ≡]> cd .\shared-ui\
~\Documents\remix-ts-integrated-monorepo\shared-ui [yarn3-pnp ≡]> yarn why @remix-run/react
└─ remix@workspace:remix
   └─ @remix-run/react@npm:1.17.1 [f6918] (via npm:^1.17.1 [f6918])
```

**Comment by airjp73** [comment] 2023-09-29 17:53
I tinkered with this for a couple minutes, but no luck. There were multiple extraneous errors caused by missing dependencies in the monorepo itself. And after adding those deps, I'm still not able to get past this error even without using remix-validated-form.

```
YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0009: │ esbuild@npm:0.18.20 couldn't be built successfully (exit code 1, logs can be found here: 
```

> I can't remember how I checked this before because we've dropped Remix in the interim but I saw that it was including the (your) package twice.

Since you're unblocked, and we've addressed the original issue, I'm going to close this issue. If you have time to put together a clean reproduction that demonstrates only the issues with RVF, please feel free to open another issue.

**Closed by airjp73** 2023-09-29 17:53 UTC
Labels: bug
