### ISSUE TITLE
[Bug]: version 4.4.2 post empty form in low version browser

### ISSUE THREAD

**Issue by motopods** [airjp73/remix-validated-form#114] opened 2022-05-17 04:04 UTC
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- "remix-validated-form": "4.4.2"

### Please provide a link to a minimal reproduction of the issue.

todo

### Steps to Reproduce the Bug or Issue

1. Using low version browser, like chrome 69.0
2. This bug is brought in version remix-validated-form 4.4.2.

### Expected behavior

form post empty form body.

### Platform

- OS: Window
- Browser: Chrome
- Version: 69.0

**Comment by airjp73** [comment] 2022-05-17 04:40
Hi! Thanks for filling the issue. Could you provide some more details? It's not really clear what the issue is that's occurring.

**Comment by lulucas** [comment] 2022-05-17 12:08
> Hi! Thanks for filling the issue. Could you provide some more details? It's not really clear what the issue is that's occurring.

In my project, without changing the code, 4.4.1 works properly and 4.4.2 does not work. This may be related to other libraries, and I'm figuring out exactly what triggers it.

**Comment by motopods** [comment] 2022-05-17 12:11
> Hi! Thanks for filling the issue. Could you provide some more details? It's not really clear what the issue is that's occurring.

In my project, without changing the code, just the remix-validated-form version, 4.4.1 works fine, 4.4.2 doesn't work. Creating a simple new project does not reproduce it, it may be related to other libraries, I'm trying to find out exactly what triggers the problem.

**Comment by motopods** [comment] 2022-05-17 12:14
![image](https://user-images.githubusercontent.com/58200641/168807996-f67d4046-b767-45ab-b24d-ba5398d43224.png)
![image](https://user-images.githubusercontent.com/58200641/168808218-684fdd59-faf1-47d5-a01c-c5d748da811e.png)

The form post payload is empty and occurs in a low version browser.

**Comment by motopods** [comment] 2022-05-17 12:37
[#chore:](https://github.com/airjp73/remix-validated-form/commit/5baf13c759ece98a363acfc70a0585a7801db10a)

The submitter is empty for some reason.

**Comment by motopods** [comment] 2022-05-17 12:50
I have already updated my project to remix 1.4.3, it works well with remix-validated-form 4.4.1, but not 4.4.2. 

And I create a new project only have remix-validated-form 4.4.2, it works well too.

**Comment by airjp73** [comment] 2022-05-17 12:55
Does it when when using only the `Form` from remix?

**Comment by airjp73** [comment] 2022-05-17 20:28
Tagging relevant commits / code in remix itself.

* https://github.com/remix-run/remix/pull/3094/files
* https://github.com/remix-run/remix/blob/dev/packages/remix-react/components.tsx#L922-L935

Looks like this change hasn't been released in remix itself yet. It may be worth reverting for now, but I do want to keep this in-line with what remix is doing. Once they release that change, it would be good to file an issue with `remix` to see what their response is.

**Comment by airjp73** [comment] 2022-05-19 00:26
Looks like the code I reference is now released in remix 1.5.1. Could you check that version to see if it reproduces just using a plain remix `<Form />`?

**Comment by motopods** [comment] 2022-05-22 13:57
1. remix 1.5.1 + <Form />  ， works 

2 . remix 1.5.1 + remix-validated-form 4.4.3， not work

**Comment by motopods** [comment] 2022-05-22 14:14
I see https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter, the submitter in Form Submit Event only works above chrome 81. But why does remix still work, I am figuring out.

**Comment by motopods** [comment] 2022-05-22 15:13
@airjp73 I know why, before chrome 81, submitter will be null so it will fallback to use event.currentTarget.
But in remix-validated-form event.currentTarget is null, this may be related to event bubbling, currentTarget  will change!!!

**Comment by airjp73** [comment] 2022-05-22 15:18
Oh, good debugging! I know what the problem is in that case. Where we differ from remix is that our `onSubmit` is asynchronous. So we need to capture the value of `event.currentTarget` right away at the start of the event handler. If we wait until we actually need it, React will have already moved on and repurposed the event object.

**Comment by airjp73** [comment] 2022-05-22 15:31
Should be fixed in the latest beta: `remix-validated-form@4.5.0-beta.1`.

Can install with `npm install remix-validated-form@beta`.

**Comment by motopods** [comment] 2022-05-22 16:12
Yes, it's fixed.

**Comment by airjp73** [comment] 2022-05-24 03:28
Fix released in [4.5.0](https://github.com/airjp73/remix-validated-form/releases/tag/remix-validated-form-v4.5.0)

**Closed by airjp73** 2022-05-24 03:28 UTC
Labels: bug, fixed in beta
