### ISSUE TITLE
[Bug]: multi file in zfd.repeatable converted to string [object],[object]

### ISSUE THREAD

**Issue by azizrosyid** [airjp73/remix-validated-form#371] opened 2024-07-08 19:03 UTC
### Which packages are impacted?

- [ ] `@rvf/react`
- [ ] `@rvf/remix`
- [ ] `@rvf/zod`
- [ ] `@rvf/yup`
- [X] `zod-form-data`

### What version of these packages are you using?

    "zod-form-data": "^2.0.2",

### Please provide a link to a minimal reproduction of the issue.

no

### Steps to Reproduce the Bug or Issue

upload multi file with zfd.repeatable(zfd.file())

### Expected behavior

i want to upload multi file

### Screenshots or Videos

no

### Platform

- OS: macos
- Browser: Terminal

**Comment by airjp73** [comment] 2024-07-08 20:20
Hi! I'm temporarily closing this issue because I don't have enough information to address it. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) so that I can help.

If you're looking for a reference point regarding how to handle multiple files with `zfd`, you can check out [this taste case for zod-form-data](https://github.com/airjp73/remix-validated-form/blob/main/packages/zod-form-data/src/zod-form-data.test.ts#L151-L163).

**Closed by airjp73** 2024-07-08 20:20 UTC
Labels: bug
