### ISSUE TITLE
[Bug]: Replace prop not working with ValidatedForm

### ISSUE THREAD

**Issue by arpitdalal** [airjp73/remix-validated-form#54] opened 2022-02-04 18:50 UTC
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: 4.0.0

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/remix-validated-form-replace-gp2tl?file=/app/routes/index.tsx

### Steps to Reproduce

Visit the codesandbox,
- Submit the first form, this form is `<ValidatedForm>`, so this **should** create a new history stack and it **does**
- Submit the second form, this form is `<ValidatedForm replace>`, so this **should NOT** create a new history stack but it **does** **<--- _This part is not working_**
- Submit the third form, this form is `<Form>`, so this **should** create a new history stack and it **does**
- Submit the fourth form, this form is `<Form replace>`, so this **should NOT** create a new history stack and it **doesn't**

The history length is printed in the header-like section on the page.

### Expected Behavior

Visit the codesandbox,
- Submit the first form, this form is `<ValidatedForm>`, so this **should** create a new history stack and it **does**
- Submit the second form, this form is `<ValidatedForm replace>`, so this **should NOT** create a new history stack and it **doesn't** **<--- _This is expected_**
- Submit the third form, this form is `<Form>`, so this **should** create a new history stack and it **does**
- Submit the fourth form, this form is `<Form replace>`, so this **should NOT** create a new history stack and it **doesn't**

### Actual Behavior

Visit the codesandbox,
- Submit the first form, this form is `<ValidatedForm>`, so this **should** create a new history stack and it **does**
- Submit the second form, this form is `<ValidatedForm replace>`, so this **should NOT** create a new history stack but it **does** **<--- _This part is not working_**
- Submit the third form, this form is `<Form>`, so this **should** create a new history stack and it **does**
- Submit the fourth form, this form is `<Form replace>`, so this **should NOT** create a new history stack and it **doesn't**

The history length is printed in the header-like section on the page.

**Comment by arpitdalal** [comment] 2022-02-04 18:53
And after updating the `remix-validated-form` to `4.0.0` from `4.0.0.-Beta` in the [codesandbox](https://codesandbox.io/s/github/airjp73/remix-validated-form/tree/main/apps/bug-repro) (provided in the bug report), the submit button gets stuck on `Submitting....` but the name entered in the textbox actually comes back so the request is done but the button is stuck in the loading state.

**Comment by airjp73** [comment] 2022-02-04 22:23
Thanks for the detailed reproduction! I know what the issue is and should have a fix later tonight or tomorrow.

**Comment by airjp73** [comment] 2022-02-05 00:05
Fixed now in v4.0.1. https://codesandbox.io/s/remix-validated-form-replace-forked-qdbnv

**Closed by airjp73** 2022-02-05 00:05 UTC
Labels: bug
