### ISSUE TITLE
[Bug]: Error when using with Immer 10

### ISSUE THREAD

**Issue by Minivera** [airjp73/remix-validated-form#312] opened 2023-08-07 14:25 UTC
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: `^5.0.1`
- `@remix-validated-form/with-zod`: `^2.0.6`
- `immer`: `^10.0.2` 

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/p/sandbox/amazing-frost-2g4gy4

### Steps to Reproduce the Bug or Issue

1. Open the demo on codesandbox and start the app
2. See the crash on load

### Expected behavior

I would expect the library to work with any version of immer installed locally, since the library should export its own version of immer? Seems like NPM is picking up the locally installed version instead, and the library does not support v10.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 114.0.5735.199

**Comment by airjp73** [comment] 2023-08-11 16:04
Looks like zustand has immer as a peer dependency and _it_ is picking up the local version of immer. I don't think it makes sense for immer to be a required peer dependency of this library so I'll have to dig a bit to figure out the best solution for this. Maybe there's a way to force zustand to resolve to RVF's version of immer.

<img width="350" alt="Screenshot 2023-08-11 at 12 01 54 PM" src="https://github.com/airjp73/remix-validated-form/assets/25882770/7cb5e452-353e-4ec7-b7c5-43cb42bb4aec">

**Comment by Minivera** [comment] 2023-08-22 19:51
Would it make sense to update the version of `immer` of the library to v10? I'm not sure what the breaking changes are yet, but I could try making a PR for it if it helps.

**Comment by airjp73** [comment] 2023-08-22 20:14
Could you try it with version `5.1.1-beta.0` to see if that fixes the error?

**Comment by Minivera** [comment] 2023-08-22 20:52
👍 Will do and then let you know

**Comment by Minivera** [comment] 2023-08-24 18:58
It works great on the codesandbox, will try on our app locally then edit this comment: https://codesandbox.io/p/sandbox/heuristic-firefly-4y96td

**Comment by airjp73** [comment] 2023-09-22 13:13
Hi! Sorry for the slow turnaround. Could you post a reproduction of the new error so I can debug it?

**Comment by airjp73** [comment] 2023-09-22 13:50
The initial fix is now released in 5.1.2.

**Comment by airjp73** [comment] 2023-09-22 14:29
Nevermind, I've managed to reproduce the issue. I've rolled back the initial fix in 5.1.3 because of the dynamic require issue.

**Comment by Minivera** [comment] 2023-09-22 15:01
I wasn't able to reproduce the issue in a codesandbox and could not figure out why it was failing in our local app, so we've moved forward with locking our own version of immer for now. Do you have a sandbox where you managed to reproduce the issue? I'd be curious as to what caused it.

**Comment by airjp73** [comment] 2024-08-08 20:46
RVF v6 has been released 🎉 

In v6, I've upgraded the versions of zustand and immer that this library is using, so I'm hoping this is no longer an issue. If this is still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).

**Closed** 2024-08-08 21:02 UTC
Labels: bug
