### ISSUE TITLE
[Bug]: `zfd.formData` should work with Zod unions

### ISSUE THREAD

**Issue by aaronadamsCA** [airjp73/remix-validated-form#249] opened 2023-02-24 11:33 UTC
### Which packages are impacted?

- [ ] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [X] `zod-form-data`

### What version of these packages are you using?

- "zod": "3.20.6",
- "zod-form-data": "2.0.0"

### Please provide a link to a minimal reproduction of the issue.

Happy to provide a minimal reproduction once the starter is fixed! It's currently broken.

### Steps to Reproduce the Bug or Issue

```ts
const FormData = zfd.formData(
  z.union([
    z.object({
      intent: z.literal("foo"),
      foo: zfd.numeric(),
    }),
    z.object({
      intent: z.literal("bar"),
      bar: zfd.text(),
    }),
  ])
);

const formData = FormData.parse(new URLSearchParams("intent=foo&foo=1"));
```

Error: `TypeError: Cannot read properties of undefined (reading '_parseSync')`

The issue is also reproducible with `z.discriminatedUnion()`.

### Expected behavior

Successful parse.

### Platform

Happening both server-side (Cloudflare Pages) and client-side (Edge 110).

**Comment by airjp73** [comment] 2023-02-24 14:26
Hi! I tried running your code exactly (with the same package versions) and I wasn't able to reproduce the issue. Could you provide a reproduction? Even if it's just a repo or some other Codesandbox template, that would be really helpful.

**Comment by aaronadamsCA** [comment] 2023-03-10 16:28
Sorry, I just haven't had the chance to create a reproduction of this yet. It is on my list. You can close in the meantime if you prefer - regardless I will get you the repro when I'm able.

**Comment by airjp73** [comment] 2023-06-13 17:11
Hi! I'm going to close the issue for now as I'm not able to reproduce. Please feel free to open another issue with a reproduction if this is still a problem. 😄

**Closed by airjp73** 2023-06-13 17:11 UTC
Labels: bug
